<table class="pickuppoints">
    <thead>
        <tr>
            <td><?php echo __('Pickup Point'); ?></td>
            <td><?php echo __('Shipping Method'); ?></td>
            <td></td>
        </tr>
    </thead>
    <tbody>
    <?php
    $pickupPoints = $block->getEnabledPickupsItems();

    foreach ($pickupPoints as $item) { ?>
            <tr>
                <td><?php echo $item->getName(); ?></td>
                <td><?php echo $item->getShippingMethod(); ?></td>
                <td>
                    <a href="<?php echo $item->getGoogleMapsURL(); ?>" title="<?php echo __('Open in Google Maps'); ?>"
                       target="_blank"><?php echo __('Open in Google Maps'); ?></a>
                </td>
            </tr>
        <?php
    } ?>
    </tbody>
</table>

<?php
    if ($pickupPoints->getSize() == 0) {
        echo __('There are no pickup points available');
    }?>

